version: "3.8"

networks:
    inception:
        name: inception
        driver: bridge

services:
    nginx:
        container_name: nginx
        env_file: .env
        ports:
            - "80:80"
        networks:
            - inception
        build: requirements/nginx
        restart: unless-stopped
    mariadb:
        container_name: mariadb
        env_file: .env
        depends_on:
            - nginx
        networks:
            - inception
        build: requirements/mariadb
        restart: unless-stopped
        # volumes:
        #     - mariadb:/var/lib/mysql
    wordpress:
        container_name: wordpress
        env_file: .env
        depends_on:
               - mariadb
        networks:
            - inception
        build: requirements/wordpress
        restart: unless-stopped
        volumes:
            - wordpress:/var/www/html
volumes:
    wordpress:
        driver: local
        driver_opts:
            type: none
            device: /home/tlafay/data/wordpress
            o: bind
    mariadb:
        driver: local
        driver_opts:
            type: none
            device: /home/tlafay/data/mariadb
            o: bind