version: "3.8"

networks:
    inception:
        name: inception
        driver: bridge

services:
    nginx:
        container_name: nginx
        ports:
            - "80:80"
        networks:
            - inception
        build: requirements/nginx
        restart: unless-stopped
    mariadb:
        container_name: mariadb
        depends_on:
            - nginx
        networks:
            - inception
        build: requirements/mariadb
        environment:
            MYSQL_ROOT_PASSWORD: somewordpress
            MYSQL_DATABASE: wordpress
            MYSQL_USER: wordpress
            MYSQL_PASSWORD: wordpress
        restart: unless-stopped
    wordpress:
        container_name: wordpress
        depends_on:
               - mariadb
        networks:
            - inception
        build: requirements/wordpress
        environment:
            WORDPRESS_DB_HOST: db:3306
            WORDPRESS_DB_USER: wordpress
            WORDPRESS_DB_PASSWORD: wordpress
            WORDPRESS_DB_NAME: wordpress
        restart: unless-stopped