version: "3.8"

networks:
    inception:


services: 
    nginx:
        container_name: nginx
        ports:
            - "80:80"
        networks:
            - inception
        build:
            context: .
            dockerfile: requirements/nginx/Dockerfile
    mariadb:
        container_name: mariadb
        ports:
            - "3306:3306"
        networks:
            - inception
        build:
            context: .
            dockerfile: requirements/mariadb/Dockerfile