version: "3.8"

networks:
    inception:
        name: inception
        driver: bridge


services:
    nginx:
        container_name: nginx
        ports:
            - "80:80"
        networks:
            - inception
        build: requirements/nginx
        restart: unless-stopped
    mariadb:
        container_name: mariadb
        depends_on:
            - nginx
        networks:
            - inception
        build: requirements/mariadb
        volumes:
            - 
        restart: unless-stopped
    wordpress:
        container_name: wordpress
        depends_on:
               - mariadb
        networks:
            - inception
        build: requirements/wordpress
        restart: unless-stopped